site_name: bpm v2025.1 DOCUMENTATION

# markdown_extensions:
#     - pymdownx.highlight
#     - pymdownx.inlinehilite
#     - pymdownx.tabbed:
#         alternate_style: true
#     - pymdownx.snippets
#     - pymdownx.critic
#     - pymdownx.caret
#     - pymdownx.keys
#     - pymdownx.mark
#     - pymdownx.tilde
#     - attr_list
#     - md_in_html
#     - admonition
#     - pymdownx.details
#     - pymdownx.superfences:
#         custom_fences:
#           - name: mermaid
#             class: mermaid
#             format: !!python/name:pymdownx.superfences.fence_code_format
#     - tables
#     - pymdownx.emoji:
#         emoji_index: !!python/name:materialx.emoji.twemoji
#         emoji_generator: !!python/name:materialx.emoji.to_svg

# plugins:
#  - git-revision-date
#  - search
#  - markmap
#  - mkdocs-video

dev_addr: '172.30.72.43:8001'

theme:
    #name: material
    name: readthedocs
#     logo: favicon.png
#     custom_dir: overrides
#     highlightjs: true
#     palette:
#         primary: black
#         scheme: default
#     features:
#         - navigation.tabs
#         - navigation.top
#         - content.tabs.link

nav:
    - 1. Getting Started:
        - 1.1. Introduction: introduction.md
        - 1.2. Installation: installation.md
        - 1.3. First Steps with bpm: first_step.md
        - 1.4. bpm: tutorial.md
    - 2. Bpm Guide:
        - 2.1. BPM Overview: why.md
        - 2.2. Creating a New Package: commands/bpm_new.md
        - 2.3 Commands:
            - 2.3.1. bpm: commands/bpm.md
            - 4.1.2. bpm help: commands/bpm_help.md
            - 4.1.3. bpm version: commands/bpm_version.md
            - 4.1.3. bpm plugins: commands/bpm_plugins.md
            - 4.1.3. bpm config: commands/bpm_config.md
            - 4.2.1. bpm build: commands/bpm_build.md
            - 4.2.2. bpm doc: commands/bpm_doc.md
            - 4.2.3. bpm run: commands/bpm_run.md
            - 4.2.4. bpm doc: commands/bpm_package.md
            - 4.3.1. bpm add: commands/bpm_add.md
            - 4.3.2. bpm remove: commands/bpm_remove.md
            - 4.3.3. bpm install: commands/bpm_install.md
            - 4.3.4. bpm update: commands/bpm_update.md
            - 4.3.5. bpm list: commands/bpm_list.md
            - 4.3.6. bpm search: commands/bpm_search.md
            - 4.3.7. bpm addsrc: commands/bpm_addsrc.md
        - 4.4. Publishing Commands:
            - 4.4.1. bpm publish: commands/bpm_publish.md
            - 4.4.2. bpm unpublish: commands/bpm_unpublish.md


# extra_css:
#     - stylesheets/extra.css
# extra:
#     social:
#         - icon: fontawesome/brands/twitter
#           link: https://twitter.com/OrixTwil
#         - icon: fontawesome/brands/youtube
#           link: https://www.youtube.com/user/jede06600/videos
